[gateway]
id = "aetheric-edge-001"
name = "Aetheric Edge Device"
location = "Building A, Floor 2"
description = "Production edge device for monitoring and control"

[mqtt]
host = "mqtt.example.com"
port = 1883
username = "edge-device"
password = "your-password-here"
tls = false
# For TLS connections, provide certificate paths:
# ca_cert_path = "/etc/ssl/certs/ca.pem"
# client_cert_path = "/etc/ssl/certs/client.pem"
# client_key_path = "/etc/ssl/private/client.key"

[health]
report_interval_seconds = 30
metrics_enabled = true

[plugins]
# Default: Install plugins in user home directory (no sudo required)
# Use ~/.aetheric/plugins for all normal usage
install_dir = "~/.aetheric/plugins"
temp_dir = "~/.aetheric/tmp"
# Special cases only: Use system directories if running as system service
# install_dir = "/opt/aetheric-edge/plugins"  # Only for production deployment
# temp_dir = "/tmp/aetheric-edge"             # Only for production deployment
docker_enabled = true
max_concurrent_installs = 2

[ssh]
enabled = true
port = 22
max_sessions = 5
session_timeout_minutes = 60